homeassistant: !include homeassistant.yaml

system_health:

http: !include http.yaml
    
#my_config
config:

mobile_app:

# Discover some devices automatically
discovery:

# ==== # ==== # ~ BELOW IS A PARTIAL CONFIGURATION OF EACH ENTITY ~ # ==== # ==== #
xiaomi_aqara: !include xiaomi_aqara.yaml
remote: !include remote.yaml
media_player: !include media_player.yaml
#google_assistant: !include google_assistant.yaml
#googlehome: !include googlehome.yaml
#panel_iframe: !include panel_iframe.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
#automation: !include automations.yaml
notify: !include notify.yaml
#yeelight: !include yeelight.yaml
history: !include history.yaml
recorder: !include recorder.yaml
influxdb: !include influxdb.yaml
#camera: !include camera.yaml
hacs: !include hacs.yaml
google: !include google.yaml #google calendar
unifi: !include unifi.yaml
#person: !include person.yaml
device_tracker: !include device_tracker.yaml
zone: !include zone.yaml
#switch: !include switch.yaml
script: !include scripts.yaml
sensor: !include sensor.yaml
#grocy: !include grocy.yaml
logger: !include logger.yaml
#smartir: !include smartir.yaml
#rest_command: !include rest_command.yaml

# ==== # ==== # ~ BELOW IS A LAZY COMPONENT MATERIAL ~ # ==== # ==== #
#- service: notify.mobile_app_mi_phone
#  data:
#    message: Anne has arrived home

#google_keep:
#  username: "fanul.doang@gmail.com"
#  password: "vdrvpnfttffccozd

fastdotcom:
  scan_interval:
    minutes: 120

input_boolean: 
  guard_home:
    name: guarding home
    initial: off
    icon: mdi:security

input_datetime:
  both_date_and_time:
    name: Input with both date and time
    has_date: true
    has_time: true

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say



