homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -6.1741
  longitude: 106.8296
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jakarta
  # Customization file
  customize: !include customize.yaml

# websocket api
websocket_api:

#device tracker
device_tracker:

  #auth-TOKEN-X
  auth_providers:
    - type: homeassistant

fastdotcom:
  scan_interval:
    minutes: 120

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Discover some devices automatically
#discovery:

# ==== # ==== # ~ BELOW IS A PARTIAL CONFIGURATION OF EACH ENTITY ~ # ==== # ==== #

xiaomi_aqara: !include xiaomi_aqara.yaml
remote: !include remote.yaml
sensor: !include sensor.yaml
media_player: !include media_player.yaml
google_assistant: !include google_assistant.yaml
googlehome: !include googlehome.yaml
panel_iframe: !include panel_iframe.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
