homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -6.1741
  longitude: 106.8296
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jakarta
  # Customization file
  customize: !include customize.yaml

  #auth-TOKEN-X
  auth_providers:
    - type: homeassistant
#my_config
config:

#logger:
#  logs:
#      custom_components.hacs: debug

#hacs:
#  token: f707f8c80cc54c93779c540a6d1c7614baf8ff95

mobile_app:

# websocket api
websocket_api:

#device tracker
device_tracker:

fastdotcom:
  scan_interval:
    minutes: 120

input_boolean: 
  guard_home:
    name: guarding home
    initial: off
    icon: mdi:security

# Configure a default setup of Home Assistant (frontend, api, etc)
#default_config:

input_datetime:
  both_date_and_time:
    name: Input with both date and time
    has_date: true
    has_time: true

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Discover some devices automatically
discovery:

#rest command
rest_command:
  sonoff_slampher_stat:
    url: 'http://192.168.1.17/cm?user=admin&password=hakimpalace100&cmnd=power'
    
#- service: notify.mobile_app_mi_phone
#  data:
#    message: Anne has arrived home

yeelight:
  devices:
    192.168.1.14:
      name: yeelight strip
      model: strip1

#google_keep:
#  username: "fanul.doang@gmail.com"
#  password: "vdrvpnfttffccozd

# ==== # ==== # ~ BELOW IS A PARTIAL CONFIGURATION OF EACH ENTITY ~ # ==== # ==== #
xiaomi_aqara: !include xiaomi_aqara.yaml
remote: !include remote.yaml
media_player: !include media_player.yaml
google_assistant: !include google_assistant.yaml
#googlehome: !include googlehome.yaml
panel_iframe: !include panel_iframe.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
notify: !include notify.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

grocy:
  url: "http://192.168.1.33:9192/api/"
  api_key: "TCHW5GH43z5qUH8FQFKV5PPqsfLzNiXIw7wFXsWURZDqJbLNXC"
  sensor:
    - enabled: true