homeassistant:
  # Name of the location where Home Assistant is running
  name: Hakim Palace
  # Location required to calculate the time the sun rises and sets
  latitude: -6.1741
  longitude: 106.8296
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Asia/Jakarta
  # Customization file
  customize: !include customize.yaml

  #auth-TOKEN-X
  auth_providers:
    - type: homeassistant

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# websocket api
websocket_api:

fastdotcom:
  scan_interval:
    minutes: 120

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

#xiaomi -==-==-==-
xiaomi_aqara:
  gateways:
  - mac: 7c:49:eb:1b:9c:00  
    key: cud4g6bdmu7aadrg
    
remote:
  - platform: xiaomi_miio
    name: "remote universal"
    host: 192.168.1.16
    token: c04af39d45ee69b633721d6d8063eb21
    slot: 1
    timeout: 30
    hidden: false


# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Discover some devices automatically
#discovery:

# Sensors
sensor:
  # Weather prediction
  - platform: yr

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
panel_iframe: !include panel_iframe.yaml